#define SCREEN_WIDTH 2560 / 2
#define SCREEN_HEIGHT 1440 / 2

#define MAX_N_ENTITIES 1024

#define GUI_TEXT_MAX_N_CHARS 32
#define GUI_FONT_ASPECT 0.5
#define GUI_FONT_TRACKING 0.0025
#define MAX_N_POINT_LIGHTS_TO_RENDER 128

#define GBUFFER_WIDTH SCREEN_WIDTH / 1
#define GBUFFER_HEIGHT SCREEN_HEIGHT / 1
