#pragma once

#define SCREEN_WIDTH 2560
#define SCREEN_HEIGHT 1440

#define MAX_N_ENTITIES 8192

#define GUI_FONT_TEXTURE_WIDTH 1504
#define GUI_FONT_TEXTURE_HEIGHT 34
#define GUI_FONT_GLYPH_WIDTH 16

#define GUI_TEXT_MAX_N_CHARS 32
#define GUI_FONT_ASPECT 0.5
#define MAX_N_POINT_LIGHTS_TO_RENDER 128

#define GBUFFER_WIDTH SCREEN_WIDTH
#define GBUFFER_HEIGHT SCREEN_HEIGHT
#define OVERLAY_BUFFER_WIDTH SCREEN_WIDTH
#define OVERLAY_BUFFER_HEIGHT SCREEN_HEIGHT
