#define DEFAULT_TRANSFORMATION_SCALE vec3_ones
#define DEFAULT_TRANSFORMATION_ROTATION vec3_zeros
#define DEFAULT_TRANSFORMATION_POSITION vec3_zeros

#define DEFAULT_CAMERA_FOV deg2rad(45.0)
#define DEFAULT_CAMERA_NEAR 0.1
#define DEFAULT_CAMERA_FAR 100.0
#define DEFAULT_CAMERA_ASPECT 16.0 / 9.0

#define DEFAULT_MATERIAL_DIFFUSE_COLOR vec3(0.8, 0.8, 0.8)
#define DEFAULT_MATERIAL_AMBIENT_COLOR vec3(0.08, 0.08, 0.08)
#define DEFAULT_MATERIAL_SPECULAR_COLOR vec3_ones
#define DEFAULT_MATERIAL_SHININESS 64.0

#define DEFAULT_POINT_SHADOW_NEAR_PLANE 0.1
#define DEFAULT_POINT_SHADOW_FAR_PLANE 50.0
#define DEFAULT_POINT_SHADOW_MIN_N_SAMPLES 8
#define DEFAULT_POINT_SHADOW_MAX_N_SAMPLES 64
#define DEFAULT_POINT_SHADOW_DISK_RADIUS 0.01
#define DEFAULT_POINT_SHADOW_BIAS_MIN 0.001
#define DEFAULT_POINT_SHADOW_BIAS_MAX 0.01

#define DEFAULT_POINT_LIGHT_COLOR vec3_ones
#define DEFAULT_POINT_LIGHT_ENERGY 100.0
